module.exports = {
    admin: { edit: "v1/menu/admin-users/edit" },
    fileManager: { view: "v1/menu/file-manager/view" },
    roles: { edit: "v1/menu/roles/edit" },
    feature: { edit: "v1/menu/feature/edit" },
    module: { edit: "v1/menu/module/edit" },
    apiClient: { edit: "v1/menu/ip-whitelisting/edit" },
    cache: { view: "v1/menu/cache-config/view" },
    settings: { edit: "v1/menu/settings/edit" },
    categories: { edit: "v1/menu/categories/edit" },
    tags: { edit: "v1/menu/tags/edit"},
    blogs: { edit: "v1/menu/blogs/edit" },
    gallery: { edit: "v1/menu/gallery/edit" },
    faq: { edit: "v1/menu/faq/edit" },
    city: { edit: "v1/menu/city/edit" },
    developer: { edit: "v1/menu/developer/edit" },
    propertyType: { edit: "v1/menu/property-type/edit" },
    amenities: { edit: "v1/menu/amenities/edit" },
    emailTemplate: { edit: "v1/menu/email-template/edit" },
};
